sudo: required

language: python
python:
  - 3.6

services:
  - docker

before_install:
  - docker build -t react-native-build . > build.log 2>&1

install:
  - docker run -d --name rnbt -t react-native-build

script:
  - docker ps | grep -q rnbt
